Fix before_update
2024-09-10 08:47:13,149 INFO  [ckanext.schemingdcat.harvesters.xls] Dataset dates - Harvest 
date: 2024-09-10 and Previous date: 2024-08-27 00:00:00
Traceback (most recent call last):
  File "/usr/bin/ckan", line 8, in <module>
    sys.exit(ckan())
  File "/usr/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/srv/app/src/ckanext-harvest/ckanext/harvest/cli.py", line 249, in fetch_consumer
    utils.fetch_consumer()
  File "/srv/app/src/ckanext-harvest/ckanext/harvest/utils.py", line 345, in fetch_consumer
    fetch_callback(consumer, method, header, body)
  File "/srv/app/src/ckanext-harvest/ckanext/harvest/queue.py", line 497, in fetch_callback
    fetch_and_import_stages(harvester, obj)
  File "/srv/app/src/ckanext-harvest/ckanext/harvest/queue.py", line 515, in fetch_and_impor
t_stages
    success_import = harvester.import_stage(obj)
  File "/srv/app/src/ckanext-schemingdcat/ckanext/schemingdcat/harvesters/xls.py", line 1113
, in import_stage
    err = harvester.before_update(harvest_object, package_dict, harvester_tmp_dict)
TypeError: before_update() missing 1 required positional argument: 'harvester_tmp_dict'